# Generated by Django 5.2.1 on 2025-06-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_staff', models.IntegerField(default=0)),
                ('active_courses', models.IntegerField(default=0)),
                ('avg_attendance_rate', models.FloatField(default=0.0)),
                ('avg_exam_scores', models.FloatField(default=0.0)),
            ],
        ),
    ]
