# Generated by Django 5.2.1 on 2025-06-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_photo',
        ),
    ]
