# Generated by Django 5.2.1 on 2025-06-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_created_by_mark_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='uploaded_by',
        ),
    ]
