# Generated by Django 5.2.1 on 2025-05-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
