# Generated by Django 5.2.1 on 2025-06-05 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_time', 'On Time'), ('late', 'Late')], default='pending', max_length=20),
        ),
    ]
