# Generated by Django 5.2.1 on 2025-06-10 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentfile_assignmentimage_assignmentlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assigned_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
