# Generated by Django 5.2.1 on 2025-06-09 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentfile_assignmentimage_assignmentlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
