# Generated by Django 5.2.1 on 2025-06-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submission_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='uploaded_by',
        ),
    ]
