# Generated by Django 5.2.1 on 2025-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_students'),
        ('assignments', '0005_remove_submission_uploaded_by'),
    ]

    operations = [
    ]
