# Generated by Django 5.2.1 on 2025-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetableentry_period_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='period_number',
            field=models.PositiveIntegerField(help_text='Period number in the day'),
        ),
    ]
