# Generated by Django 5.2.1 on 2025-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timetableentry_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
    ]
