# Generated by Django 5.2.1 on 2025-06-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetableentry_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='created_by',
        ),
    ]
