# Generated by Django 5.2.1 on 2025-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_created_at_attendance_updated_at_and_more'),
        ('attendance', '0002_attendance_staff'),
    ]

    operations = [
    ]
