# Generated by Django 5.2.1 on 2025-06-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_merge_20250615_1210'),
        ('attendance', '0004_alter_attendance_course_alter_attendance_student'),
    ]

    operations = [
    ]
